packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  typescript: ^5.9.3
  tsup: ^8.4.1
  vite: ^6.0.5

  "@biomejs/biome": 2.3.10
  ultracite: 7.0.5

  clsx: ^2.1.1
  tailwind-merge: ^3.4.0

  "@types/react": ^19.2.7
