packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  # Build tools (shared across multiple packages)
  typescript: ^5.9.3
  tsup: ^8.4.1
  vite: ^6.0.5

  # Linting & formatting (root + www)
  "@biomejs/biome": 2.3.10
  ultracite: 7.0.5

  # CSS utilities (www + shared + react)
  clsx: ^2.1.1
  tailwind-merge: ^3.4.0

  # React types (www + react)
  "@types/react": ^19.2.7
